version: "3.6"

services:
  get:
    image: mattwiater/rest-server
    networks:
      - app-entry
      - rhswarm
    deploy:
      replicas: 10
      labels:
        traefik.docker.network: app-entry
        traefik.backend: get
        traefik.backend.loadbalancer.method: drr
        #traefik.backend.circuitbreaker.expression: "LatencyAtQuantileMS(50.0) > 1"
        traefik.backend.healthcheck.path: "/"
        traefik.frontend.rule: "Method: GET;Path: /api;PathPrefixStrip:/api"
        traefik.port: 9001

  post:
    image: mattwiater/rest-server
    networks:
      - app-entry
      - rhswarm
    deploy:
      labels:
        traefik.docker.network: app-entry
        traefik.backend: post
        traefik.backend.loadbalancer.method: wrr
        traefik.frontend.rule: "Method: POST;Path: /api;PathPrefixStrip:/api"
        traefik.port: 9001

networks:
  app-entry:
    external: true
  rhswarm:
    external: true