# REF: https://prometheus.io/docs/guides/cadvisor/
# REF: https://github.com/google/cadvisor/blob/master/docs/api_v2.md

version: '3.3'
services:

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    networks:
      - app-entry
      - rhswarm
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  app-entry:
    external: true
  rhswarm:
    external: true