# REF: https://prometheus.io/docs/guides/cadvisor/
# REF: https://github.com/google/cadvisor/blob/master/docs/api_v2.md

version: '3.3'
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - rhswarm
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    networks:
      - rhswarm
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - rhswarm
    ports:
      - 6379:6379

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - rhswarm

networks:
  rhswarm:
    external: true

configs:
  prometheus.yml:
    external: true