# REF: https://prometheus.io/docs/guides/cadvisor/

version: '3.2'
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - rhswarm
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    networks:
      - rhswarm
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - rhswarm
    ports:
      - 6379:6379

networks:
  rhswarm:
    external: true